# Build the Express.js server
FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma/

COPY .env ./

COPY tsconfig.json ./

COPY . .

RUN npm install

RUN npx prisma generate

RUN npm run build

WORKDIR /app

EXPOSE 3333

CMD npm start